### ISSUE TITLE
buy of streak / wager doens't work anymore

### ISSUE THREAD

**Issue by TiloGit** [alexsanjoseph/duolingo-save-streak#2]
probable upstream issue of: https://github.com/KartikTalwar/Duolingo/issues/63

**Comment by alexsanjoseph** [comment]
Yeah looks like it - My scripts also started failing

**Comment by TiloGit** [comment]
fixed upstream, see linked issue

**Comment by alexsanjoseph** [comment]
Thanks, will take a look

**Comment by alexsanjoseph** [comment]
They seem to have fixed the issue from the API side from October 31st - Scripts are working fine without any change
